### ISSUE TITLE
Plugin needs to display which version of conveyor this is

### ISSUE THREAD

**Issue by milutz** [samtecspg/conveyor#129]
The plugin needs to display which version of conveyor this is and instructions also have to be provided on how to how to set that in the process of building a release

**Comment by malave** [comment]
On `plugin` it appear under the logo, on the `API` you can get it by doing a GET on `/system/info`.

Both versions (plugin and API) are taken from the `package.json` file of each project, with the new EUI update the version can be different from the kibana version since there is another field for purpose.

Currently they are not reflecting the same version or the correct one, but when we merge `2.0.0` we can put them in sync.
