### ISSUE TITLE
Create _index system variable

### ISSUE THREAD

**Issue by malave** [samtecspg/conveyor#38]
@wrathagom
- Use an existing value to use as an ES index name
- This value should comply with ES rules for naming an index
- Try not to use and environment variable for this

Post findings here before coding anything.

**Comment by wrathagom** [comment]
@malave I am proposing that we add a new field to the basic information section called Index Name. That populates the `_index` system variable. It defaults to an ES friendly version of the name. I'm thinking using a tool like dashify? but can be overridden.

Flows will then add data into ES under that index. Or if not that index directly then using that as an index alias.

I see this as an enabler to #56 because you'll have to know what to delete in ES. If we always link the data back to that `_index` then you'll always know where it is in ES.

![truncate reload sql server flow mockup](https://user-images.githubusercontent.com/1779894/31254280-f3479e66-a9f5-11e7-93c8-bd717146e250.png)

**Comment by wrathagom** [comment]
@malave I see that this is in, but I intended for the default value to be equal to the dashified channel name not the name of the source... I should've been more clear.

I'm worried that with the current setup users will be too likely to override/mix data.
