### ISSUE TITLE
Can't Utilize Boolean parameters

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#51]
Since we moved away from stringifying the flow before uploading I can no longer use boolean parameter types. I have to put the templating syntax in a string to be valid JSON:

```
      {
        "id": "{{_id}}-18",
        "type": "http request",
        "name": "",
        "method": "POST",
        "ret": "{{PARAMETER}}",
        "url": "elasticsearch:9200/{{_id}}/_delete_by_query",
        "tls": "",
        "x": 630,
        "y": 140,
        "wires": [
          [
            "{{_id}}-19"
          ]
        ]
      }
```

But this fails because "false" doesn't equal false :) We either need to move back to stringifying. Which was always problematic for me, but I don't remember why. Or figure out a new solution.

**Comment by malave** [comment]
@wrathagom so after several tries it seems that we would have to revert back t having the stringified flow in the template instead of the JSON object so we can have a parameter in the string with any surrounding  quotation marks.

The problem with this is approach is that if we need to modify the nodered flow we need to do some manual JSON.parse/stringify before saving, instead of just modifying the JS object and saving.

I will continue making this changes.

**Comment by wrathagom** [comment]
That's fine using a solution like what is in the two repos I have created we can still modify the json and have an install script that does the appropriate packaging...

**Comment by milutz** [comment]
Note to mike: this is an issue because the JSON gets de-mustached by the api, and true/false don’t get quoted. Where as everything else can get away with being quoted - currently the way they are doing the mustash stuff is to quote it

**Comment by wrathagom** [comment]
Closing, because I believe I have this one licked.

Most all of the magic now happens in the installation file [here](https://github.com/samtecspg/conveyor/blob/master/channel-sources/install-channels.py#L56). I am going through the parameters and finding any that are of the type `boolean` if they are I search the stringified flow and if the parameter is wrapped In double quotes I remove them.
