### ISSUE TITLE
More Plugin Styling Issues

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#60]
Vertical Alignment is off on this create text:
<img width="449" alt="2017-10-02_21-29-14" src="https://user-images.githubusercontent.com/1779894/31107314-98441d2e-a7bf-11e7-818a-360744307b97.png">

Font weight and color corrections:
<img width="887" alt="2017-10-02_21-15-37" src="https://user-images.githubusercontent.com/1779894/31107312-983fa6ae-a7bf-11e7-847e-f59f25eb6e9d.png">

Input box should be around all inputs in group:
<img width="975" alt="2017-10-02_21-10-26" src="https://user-images.githubusercontent.com/1779894/31107313-98421fc4-a7bf-11e7-959a-00915d5d6d8c.png">

Input styling is still off, these changes seem to fix it, but I don't know how difficult they are to actually implement.
<img width="1542" alt="2017-10-02_21-06-55" src="https://user-images.githubusercontent.com/1779894/31107346-d6f69934-a7bf-11e7-9afd-0b1b8bac8646.png">
<img width="1415" alt="2017-10-02_21-09-27" src="https://user-images.githubusercontent.com/1779894/31107347-d6fbe1e6-a7bf-11e7-922e-1d6d46f719a6.png">

**Comment by malave** [comment]
@wrathagom:

1. The `+ Create` text in the card is centered, probably it appears to be off because due to the `+ ` text. 

1. From the mocks from @broham89 it was for each input and trying to  wrap the inputs bring a problem, we are using the grid system from material ui so we can do this:

   1.  we can wrap each cell individually (as we do now),
   1.  wrap a row
   1. wrap  the entire grid (see screenshot) 

But I think what you want is only the column and leave the description helper outside, but this can't be done with this library since it doesn't provide classes to do so.

<img width="1392" alt="grid-box on entire grid" src="https://user-images.githubusercontent.com/410400/31212095-93bb60a4-a9c8-11e7-83bf-7321340cbff8.png">

**Comment by wrathagom** [comment]
Where do you see it around each input @malave this is what I am referencing https://3.basecamp.com/3813023/buckets/4512636/uploads/634103786

Maybe you've got the grid wrong for how we want to do it? Maybe you need to move the grid for the right hand area up to the top level. You'll have to use some JS wizards to align the help text then.

I vote for wrapping the entire grid for now, but add a note onto #59 to fix this at the same time.

**Comment by wrathagom** [comment]
Also on the **[+ Create]**, I mean vertical alignment not horizontal. It looks closer to the bottom of the button than the top.

@broham89 am I crazy?

**Comment by malave** [comment]
@wrathagom: yeah the vertical alignment is a little off.

I was using the html @broham89 gave me but I think it wasn't posted on basecamp (screenshot below) but I will do as you mentioned above.

![form-htm-mockup](https://user-images.githubusercontent.com/410400/31275254-be5b37e6-aac0-11e7-9c12-795429b13418.png)

**Comment by broham89** [comment]
@wrathagom I believe you are right that `+create` looks closer to the bottom. You're not crazy.

**Comment by wrathagom** [comment]
Closing as the whole UI is going to get re-implemented in EUI
