### ISSUE TITLE
Build and Test against most recent ES version

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/conveyor#65]
If I remember right we're still building/testing against 5.4. Can we try to build/test against the latest 5.5 and 5.6 releases and the 6.0 release candidate.

**Comment by milutz** [comment]
In talking with @wrathagom we are now saying we just want to jump up to 6.0 (or what is the release candidate now) now, and save the “other releases” work for later

**Comment by malave** [comment]
Tested with ES and Kibana 6.0.0-rc2:

Besides changing the configuration files there are 2 minor changes that needs to be done to be able to run the plugin with the latest kibana:
- Change `jsx` to `js`
- Change `ui/modules`:
```
 imports import modules from 'ui/modules'; 
```
to
```
 import { uiModules } from 'ui/modules';
```

Both changes are caused because Kibana is now using newer versions of Webpack and Babel and the configuration changed in it now behaves differently.

After doing this changes I was able to create and delete flows using the plugin. 
I created a branch to hold this changes until we decide to do the move to ES+Kibana 6

**Comment by wrathagom** [comment]
@malave will these changes not work for earlier versions? if so that sucks.

**Comment by malave** [comment]
@wrathagom The `uiModules` module change won't work, this is a library provided by kibana that changed on this release so it works differently on previous versions and this could break it.

**Comment by karnamonkster** [comment]
Can we somehow test & use v5.4  on 5.6.2
is there any change we need apart from version within src files?

**Comment by wrathagom** [comment]
@karnamonkster can you create a new issue for what you are wanting to accomplish. The latest release is built against ES 6.3
